1. How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.

Ans. Let say C is our final matrix. C will have dimension of n*m. Now, to compute each element in C we will need a row from A and a column from B which has lenght k. For each element we will do k mutiplications and k-1 additions. So, in total, we will do n*m*k multiplications and n*m*(k-1) additions.


2. Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?   

Ans. If you run below code, you will se multiplicatipn using numpy arrays is much faster than list multiplications.
In fact it is 1000 times faster. 
Matrix multiplication with NumPy is faster than with a list of lists because NumPy is implemented in C, while a list of lists is a Python data structure. This means that NumPy operations are executed in compiled code, which is generally faster than Python code. In addition, NumPy stores matrices in a contiguous block of memory, which makes it more efficient to perform operations on the data because it can be accessed more quickly by the CPU.

Another reason that NumPy matrix multiplication is faster is that NumPy includes optimized implementations of many common mathematical operations, including matrix multiplication. These optimized implementations are written in C and are much faster than the equivalent Python code.

In [56]:

n=30
k=67
m=50
A=[]
for i in range (n):
    row=[]
    for j in range(k):
        row.append(j)
    A.append(row)

B=[]
for i in range (k):
    row=[]
    for j in range(m):
        row.append(j)
    B.append(row)

# Using list multiplication
def list_multiply(A,B):
    C=[]
    for i in range (n):
        row=[]
        for j in range(m):
            c=0
            for l in range(k):
                c+=(A[i][l]*B[l][j])
            row.append(c)
        C.append(row)

def numply_multi(A,B):
    a=np.array(A)
    b=np.array(B)
    C=np.matmul(a,b)


# Measure the time taken to multiply the matrices using a list of lists
%timeit -n 100 -r 5 list_multiply(A,B) 

# Measure the time taken to multiply the matrices using numpy 
%timeit -n 100 -r 5 numply_multi(A,B) 



12 ms ± 165 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)
333 µs ± 754 ns per loop (mean ± std. dev. of 5 runs, 100 loops each)


3. Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?

Ans. The time complexity of finding the median of an array using the method you described would be O(n^2) because you need to make n/2 passes of the array to find the median, and each pass has a time complexity of O(n).

A better method for finding the median of an array would be to first sort the array and then return the element at index n/2 (if the array has an odd number of elements) or the average of the elements at indices n/2 and n/2 - 1 (if the array has an even number of elements). This method has a time complexity of O(n log n) because the time complexity of sorting an array is O(n log n).

In terms of time, numpy.median is way faster than both of above method. You can test it in below code.



In [59]:

# Find the median of an array by making n/2 passes of the array
def find_median_brute(arr):
    arr = sorted(arr)
    if len(arr) % 2 == 1:
        return arr[len(arr) // 2]
    else:
        return (arr[len(arr) // 2] + arr[len(arr) // 2 - 1]) / 2

 # Find the median of an array by sorting it and then returning the element at index n/2 
 # (if the array has an odd number of elements) or the average of the elements at indices n/2 and n/2 - 1 
 # (if the array has an even number of elements)
def find_median_sorted(arr):
    arr = sorted(arr)
    if len(arr) % 2 == 1:
        return arr[len(arr) // 2]
    else:
        return (arr[len(arr) // 2] + arr[len(arr) // 2 - 1]) / 2

# using numpy.median
def numpy_median(arr):
    return np.median(arr)

# testing over big array
a= np.random.rand(10000)

%timeit -n 100 -r 5 find_median_brute(a) 

%timeit -n 100 -r 5 find_median_sorted(a) 

%timeit -n 100 -r 5 numpy_median(a) 



3.2 ms ± 67.4 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)
3.15 ms ± 53 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)
105 µs ± 6.33 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)


4. What is the gradient of the following function with respect to x and y?$$ x^2y+y^3sin(x)$$ 
Ans. i) gradient with respect to y:$$ x^2+3y^2sin(x)$$   
    ii) gradient with respect to x:$$ 2xy+y^3cos(x)$$

5. Use JAX to confirm the gradient evaluated by your method matches the analytical solution corresponding to a few random values of x and y

In [ ]:
import math
import jax.numpy as jnp
import jax
import numpy as np

def f(x,y):
    return x**2*y+y**3*jnp.sin(x)

def df_dy(x,y):
    return x**2+3*y**2*math.sin(x)

def df_dx(x,y):
    return 2*x*y+y**3*math.cos(x)

# Evaluate the gradient at a few random points
for i in range(5):
    x = np.random.uniform(-5, 5)
    y = np.random.uniform(-5, 5)
    print("my method:",df_dx(x,y),df_dy(x,y))
    print("answer using JAX:",jax.grad(f, argnums=(0, 1))(x,y))


6. Use sympy to confirm that you obtain the same gradient analytically.

In [ ]:
import math
import sympy

# def f(x,y):
#     return x**2*y + y**3*sympy.sin(x)
x, y = sympy.symbols('x y')
f = x**2*y + y**3*sympy.sin(x)
g = sympy.Matrix([f]).jacobian([x, y])
g_numpy = sympy.lambdify((x, y), g, 'numpy')
def df_dy(x,y):
    return x**2+3*y**2*math.sin(x)

def df_dx(x,y):
    return 2*x*y+y**3*math.cos(x)

# Evaluate the gradient at a few random points
for i in range(5):
    x = np.random.uniform(-3, 3)
    y = np.random.uniform(-3, 3)
    print("my method:",df_dx(x,y),df_dy(x,y))
    print("answer using sympy:",g_numpy(x,y))

7. Create a Python nested dictionary to represent hierarchical information. We want to store record of students and their marks.

In [11]:
records={
    "2022": {
            "Branch 1":{
                        "Roll number 1":{"name":"xyz","marks":{"MATHS":100,"ENGLLISH":70,}},
                        "Roll number 2":{},
                        },
            "Branch 2":{},
            },
    "2023": {
            "Branch 1":{},
            "Branch 2":{},
            },
    "2024": {"Branch 1":{},
             "Branch 2":{},
            },
    "2025": {"Branch 1":{},
             "Branch 2":{},
            },
}

8. Store the same information using Python classes. We have an overall database which is a list of year objects. Each year contains a list of branches. Each branch contains a list of students. Each student has some properties like name, roll number and has marks in some subjects.

In [16]:
class Student:
    def __init__(self,name,roll_number,grades={}):
        self.name=name
        self.roll_number=roll_number
        self.grades=grades
    
    def add_marks(self,subject,marks):
        self.grades[subject]=marks

class Branch:
    def __init__(self,branch_name,students=[]):
        self.branch_name=branch_name
        self.students=students
    def add_student(self,student):
        self.students.append(student)

class Year:
    def __init__(self,year,branches=[]):
        self.year=year
        self.branches=branches
    def add_branch(self,branch):
        self.branches.append(branch)


# storing information
Database=[]
y2022=Year("2022")
branch1=Branch("branch 1")
xyz=Student("xyz","1",{"MATHS":100,"ENGLLISH":70,})
branch1.add_student(xyz)
y2022.add_branch(branch1)
Database.append(y2022)
print(Database)



9. Using matplotlib plot the following functions on the domain: x = 0.5 to 100.0 in steps of 0.5.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

# 1. y=x
x = np.arange(0.5, 100.0, 0.5)
y = x
plt.plot(x, y)
plt.show()

# y= x^2
y = x**2
plt.plot(x, y)
plt.show()

# y=x^3/100
y = (x**3)/100
plt.plot(x, y)
plt.show()

# y=sin(x)
def f(x):
    return math.sin(x)
y = np.vectorize(f)
plt.plot(x, y(x))
plt.show()

# y=sin(x)/x
def f(x):
    return math.sin(x)/x
y = np.vectorize(f)
plt.plot(x, y(x))
plt.show()

# y=log(x)
def f(x):
    return math.log(x)
y = np.vectorize(f)
plt.plot(x, y(x))
plt.show()

#y=e^x
def f(x):
    return math.exp(x)
y = np.vectorize(f)
plt.plot(x, y(x))
plt.show()

10. Using numpy generate a matrix of size 20X5 containing random numbers drawn uniformly from the range of 1 to 2. Using Pandas create a dataframe out of this matrix. Name the columns of the dataframe as “a”, “b”, “c”, “d”, “e”. Find the column with the highest standard deviation. Find the row with the lowest mean.

In [37]:
import numpy as np
import pandas as pd

matrix = np.random.uniform(1, 2, size=(20, 5))
df = pd.DataFrame(matrix, columns=["a", "b", "c", "d", "e"])
print("column with the highest standard deviation is:", df.std().idxmax())
print("row with the lowest mean is:", df.mean(axis=1).idxmin())

column with the highest standard deviation is: d
row with the lowest mean is: 9


11. Add a new column to the dataframe called “f” which is the sum of the columns “a”, “b”, “c”, “d”, “e”. Create another column called “g”. The value in the column “g” should be “LT8” if the value in the column “f” is less than 8 and “GT8” otherwise. Find the number of rows in the dataframe where the value in the column “g” is “LT8”. Find the standard deviation of the column “f” for the rows where the value in the column “g” is “LT8” and “GT8” respectively.

In [39]:
df['f'] = df[['a', 'b', 'c', 'd', 'e']].sum(axis=1)
df['g'] = df['f'].apply(lambda x: 'LT8' if x < 8 else 'GT8')

print("number of rows with column g value=LT8:", len(df[df['g']=='LT8']))
print("Standard deviation of column 'f' for rows where column 'g' is 'LT8':",df[df['g']=='LT8']['f'].std())
print("Standard deviation of column 'f' for rows where column 'g' is 'GT8':",df[df['g']=='GT8']['f'].std())

number of rows with column g value=LT8: 13
Standard deviation of column 'f' for rows where column 'g' is 'LT8': 0.3886576394425924
Standard deviation of column 'f' for rows where column 'g' is 'GT8': 0.29585053427510544


12. Write a small piece of code to explain broadcasting in numpy.
Ans.
Broadcasting is a powerful feature of NumPy that allows arithmetic operations to be performed on arrays of different sizes. It works by "broadcasting" the smaller array across the larger array so that they have compatible shapes, and then performing the arithmetic operation element-wise on the broadcasted arrays.
Look at below example: The output of this code will be:

[[11 22 33 44]   
[15 26 37 48]   
[19 30 41 52]]   

As you can see, the 1D array b was broadcasted across the 2D array a so that they had compatible shapes, and then the element-wise addition was performed on the broadcasted arrays.


In [40]:
import numpy as np

# Create a 2D array with shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Create a 1D array with shape (4,)
b = np.array([10, 20, 30, 40])

# Add the arrays using broadcasting
c = a + b

print(c)


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


13. Write a function to compute the argmin of a numpy array. The function should take a numpy array as input and return the index of the minimum element. You can use the np.argmin function to verify your solution.

In [4]:
import numpy as np

def arg_min(arr):
    array=arr.flatten()
    min_index = 0
    for i in range(1, len(array)):
        if array[i] < array[min_index]:
            min_index = i
    # actual_index = np.unravel_index(min_index, arr.shape)
    return min_index
# Test the function with a random NumPy array
array = np.random.randint(0, 10, size=(5,6))
print("My answer:",arg_min(array))
print("actual answer:",np.argmin(array))

My answer: 23
actual answer: 23
